'use strict';
window.TERRA_LOCALES = {
  fr: {
    ui: {
      menuOpen: 'Ouvrir le menu', menuClose: 'Fermer le menu',
      watchFilm: 'Voir le film Terra AI ↗', filmStatus: 'Voir le film du projet', filmTitle: 'Film de présentation de Terra AI',
      pause: 'Mettre en pause', play: 'Lancer le défilement'
    },
    steps: [
      { kicker: '01 / OBSERVER LE TERRAIN', title: 'Commencer par écouter ce que dit la terre.', description: 'Les sondes suivent la conductivité électrique (EC), l’humidité, la température et le pH du sol. Les capteurs foliaires mesurent l’humectation et la température des feuilles, tandis que les mesures de l’air apportent le contexte environnemental. Chaque relevé est associé à une parcelle et à une zone de gestion identifiées.', input: 'Conditions physiques du sol, de la culture et de l’air', output: 'Mesures horodatées associées à une zone précise' },
      { kicker: '02 / COLLECTER LOCALEMENT', title: 'Donner au terrain son propre point d’écoute.', description: 'La Terra Box, alimentée par le solaire, recueille les mesures grâce à ses interfaces capteurs. Le contrôleur RAK3112 les traite, les organise, les associe au boîtier et à la zone, puis applique les règles locales configurées. Une commande d’irrigation validée peut fonctionner localement lorsque les équipements sont installés.', input: 'Mesures des capteurs du sol, des feuilles et de l’air', output: 'Paquets de données structurés et actions locales configurées' },
      { kicker: '03 / CONNECTER LE TERRAIN', title: 'Apporter le réseau à l’exploitation.', description: 'Les Terra Box transmettent des paquets compacts à une passerelle partagée via un réseau LoRaWAN privé. Chaque Box fonctionne sans carte SIM individuelle. La passerelle transmet les données à Terra Cloud grâce à une connexion internet disponible : Ethernet, Wi-Fi, réseau cellulaire ou équipement satellite externe.', input: 'Paquets LoRaWAN provenant de plusieurs Terra Box', output: 'Données acheminées vers le cloud par une connexion partagée' },
      { kicker: '04 / INTERPRÉTER LE CONTEXTE', title: 'Une mesure devient utile grâce à son contexte.', description: 'Terra Cloud associe chaque relevé à l’agriculteur, à la parcelle et à la saison. L’évolution des capteurs est analysée avec les résultats de Terra Lab, le stade de la culture, la météo et les événements enregistrés. Les règles et l’IA aident à repérer les situations qui nécessitent une attention et préparent l’aide à la décision agronomique.', input: 'Évolution des capteurs + analyses de laboratoire + contexte cultural et météo', output: 'Une observation, une alerte ou un projet de recommandation traçable' },
      { kicker: '05 / VALIDER PAR L’EXPERTISE', title: 'L’agronome transforme l’information en conseil.', description: 'L’agronome Terra confronte les éléments disponibles à la culture, à la référence de Terra Lab et au plan de gestion. Il confirme ou adapte la recommandation, demande une inspection ou un nouveau prélèvement si les preuves sont insuffisantes. Les conseils sur les nutriments s’appuient sur les résultats NPK du laboratoire.', input: 'Une alerte et les éléments agronomiques qui la justifient', output: 'Un conseil validé et adapté à la situation de l’agriculteur' },
      { kicker: '06 / ATTEINDRE L’AGRICULTEUR', title: 'Rendre la prochaine action claire et accessible.', description: 'Les conseils validés arrivent par SMS sur un téléphone mobile simple. Le français et les langues locales, notamment le lingala et le swahili, font partie du plan de déploiement. Les interventions, les observations de suivi et les récoltes enrichissent l’historique de l’exploitation et les décisions de la saison suivante.', input: 'Conseil validé par l’agronome et coordonnées de l’agriculteur enregistré', output: 'Un SMS pratique, une action sur le terrain et un retour d’expérience' }
    ],
    actors: [
      { kicker: 'AU CENTRE DU SYSTÈME', title: 'Donner à chaque agriculteur sa place dans l’économie agricole.', description: 'Le profil de l’exploitation réunit sa localisation, ses cultures, les informations sur le sol, son historique et ses besoins agronomiques. Les agriculteurs partagent leurs observations et leurs résultats ; en retour, ils reçoivent des conseils et sont reliés aux personnes capables de les accompagner.', from: 'Données de l’exploitation', fromDetail: 'Localisation · sol · cultures · besoins', to: 'Un secteur connecté', toDetail: 'Experts · services · marchés', icon: 'network', benefits: ['Recevoir par SMS des conseils agronomiques adaptés à chaque culture.', 'Relier les besoins identifiés aux intrants, aux aides et aux acheteurs appropriés.', 'Constituer un historique saison après saison pour mieux accompagner l’exploitation.'] },
      { kicker: 'ÉTENDRE LA PORTÉE DU SAVOIR HUMAIN', title: 'Garder l’expertise connectée au terrain.', description: 'Nos agronomes de terrain associent leur connaissance des cultures à des observations continues. Terra Laboratoire Agronomique établit et actualise l’état de référence chimique du sol. Terra relie ces informations à la même zone et à la même saison pour faciliter l’interprétation des changements et le suivi des conseils.', from: 'Observations de terrain', fromDetail: 'Évolution · alertes · stade cultural', to: 'Décisions expertes', toDetail: 'Agronomes · laboratoires', icon: 'check', benefits: ['Associer chaque résultat de laboratoire au bon agriculteur et à la bonne zone de gestion.', 'Examiner les alertes, valider les recommandations et prioriser les visites.', 'Enregistrer les conseils et les résultats du suivi pour mieux étayer les prochaines décisions.'] },
      { kicker: 'ÉCLAIRER L’ACTION PUBLIQUE', title: 'Faire parvenir les politiques agricoles jusqu’au terrain.', description: 'La plateforme nationale prévue réunit les agriculteurs enregistrés, les lieux de culture et les besoins du terrain dans une vision agricole commune. Les ministères peuvent utiliser les informations adaptées, à l’échelle régionale ou de l’exploitation, pour planifier les aides et suivre leur mise en œuvre.', from: 'Exploitations enregistrées', fromDetail: 'Zones · cultures · besoins documentés', to: 'Pouvoirs publics', toDetail: 'Ministères · services de vulgarisation', icon: 'building', benefits: ['Localiser les agriculteurs inscrits et connaître leurs productions.', 'Cibler l’accompagnement, les subventions et les interventions à partir des besoins documentés.', 'Coordonner les ONG, les coopératives et les acheteurs autour d’une même référence de terrain.'] },
      { kicker: 'MIEUX CIBLER L’ACCOMPAGNEMENT', title: 'Relier l’aide aux besoins documentés.', description: 'Les ONG et les acteurs du développement, dont des organisations comme la FAO, sont des utilisateurs envisagés de la plateforme. Terra peut relier les critères des programmes aux exploitations enregistrées pour coordonner l’appui et suivre les résultats dans le temps.', from: 'Besoins des exploitations', fromDetail: 'Situation initiale · risques · résultats', to: 'Acteurs du développement', toDetail: 'ONG · programmes agricoles', icon: 'globe', benefits: ['Identifier les agriculteurs inscrits éligibles selon leur localisation, leurs cultures et leurs besoins évalués.', 'Coordonner l’aide avec les services publics et les agronomes locaux.', 'Comparer les situations initiales et les résultats documentés pour évaluer l’impact des programmes.'] },
      { kicker: 'DES FOURNITURES ADAPTÉES AUX BESOINS', title: 'Associer les bons intrants à la bonne exploitation.', description: 'Les semenciers et les fournisseurs d’engrais ou de matériel peuvent répondre aux besoins inscrits dans le plan agronomique de l’exploitation. Terra relie cette demande à la bonne zone et au bon agriculteur, avec des choix techniques guidés par l’agronome et les analyses de laboratoire.', from: 'Plans agricoles validés', fromDetail: 'Culture · état du sol · besoins en intrants', to: 'Fournisseurs d’intrants', toDetail: 'Semences · engrais · équipements', icon: 'box', benefits: ['Comprendre les besoins des exploitations participantes et leur calendrier.', 'Organiser les livraisons selon les périodes de culture et les localisations identifiées.', 'Relier l’offre commerciale aux conseils agronomiques et aux conditions réelles du sol.'] },
      { kicker: 'RENDRE LA PRODUCTION PLUS VISIBLE', title: 'Relier les récoltes à un marché mieux organisé.', description: 'Les transformateurs et les acheteurs doivent savoir qui produit quoi, où et quand. Les profils de production prévus par Terra les relient aux exploitations et aux coopératives inscrites pour faciliter les échanges commerciaux et la planification des collectes.', from: 'Profils de production', fromDetail: 'Cultures · lieux · périodes de récolte', to: 'Acheteurs et transformateurs', toDetail: 'Approvisionnement · collecte · marchés', icon: 'truck', benefits: ['Trouver les exploitations et les coopératives identifiées qui produisent les cultures recherchées.', 'Planifier les tournées selon les localisations et les périodes de récolte prévues.', 'Réintégrer les quantités réellement récoltées et les exigences des acheteurs dans le plan de la prochaine saison.'] },
      { kicker: 'CONSTRUIRE UNE BASE DE CONNAISSANCES', title: 'Faire progresser la recherche grâce au terrain.', description: 'Les chercheurs ont besoin d’observations comparables entre zones de sol, cultures et saisons. Terra vise à associer les séries temporelles des capteurs aux analyses de laboratoire, aux interventions et aux résultats, pour soutenir la calibration et l’évaluation des modèles.', from: 'Données saisonnières', fromDetail: 'Capteurs · laboratoire · résultats', to: 'Équipes de recherche', toDetail: 'Universités · validation des modèles', icon: 'book', benefits: ['Étudier les relations entre conditions du terrain et résultats agronomiques.', 'Valider les modèles prédictifs à partir des analyses et des observations réelles.', 'Transmettre les résultats évalués aux agronomes pour améliorer les conseils pratiques.'] },
      { kicker: 'PARTAGER LES PRATIQUES AVEC LEUR CONTEXTE', title: 'Transformer les réussites en apprentissage partagé.', description: 'L’approche Terra Clone proposée repère des pratiques documentées qui pourraient être utiles dans des conditions comparables. Le type de sol, la variété, l’historique des intrants et les résultats fournissent le contexte ; un agronome vérifie leur pertinence avant de les adapter ailleurs.', from: 'Pratiques documentées', fromDetail: 'Sol · variété · actions · résultats', to: 'Exploitations comparables', toDetail: 'Adaptation · validation · apprentissage', icon: 'network', benefits: ['Documenter les pratiques réussies et les conditions qui les ont rendues possibles.', 'Identifier des parcelles comparables plutôt que copier la même recette partout.', 'Adapter les pratiques avec un agronome, puis mesurer leur efficacité locale.'] }
    ]
  }
};
